CREATE TABLE estimate(
    ebno NUMBER(4)
        CONSTRAINT ESTI_BNO_FK REFERENCES board(bno)
        CONSTRAINT ESTI_BNO_NN NOT NULL,
    eida VARCHAR2(10 CHAR)
        CONSTRAINT ESTI_IDA_NN NOT NULL
        CONSTRAINT ESTI_IDA_FK REFERENCES member(id),
    eidb VARCHAR2(10 CHAR)
        CONSTRAINT ESTI_IDB_NN NOT NULL
        CONSTRAINT ESTI_IDB_FK REFERENCES member(id),
    epoint NUMBER(3,2) DEFAULT 0
        CONSTRAINT ESTI_PTS_NN NOT NULL
);