-- faq
CREATE TABLE FAQ
(NO NUMBER CONSTRAINT NO_FAQ_PK PRIMARY KEY,
ID VARCHAR2(20 char) CONSTRAINT ID_FAQ_NN NOT NULL
                     CONSTRAINT ID_FAQ_UK UNIQUE,
PW VARCHAR2(20 char) CONSTRAINT PW_FAQ_NN NOT NULL,
TITLE VARCHAR2(50 CHAR) CONSTRAINT TITLE_FAQ_NN NOT NULL,
CONTENT VARCHAR2(1000 CHAR) CONSTRAINT CONTENT_FAQ_NN NOT NULL,
WDATE DATE DEFAULT SYSDATE);

CREATE SEQUENCE FAQ_SEQ
START WITH 1
NOMAXVALUE
NOCYCLE;