-- admin
CREATE TABLE ADMIN
(ID VARCHAR2(15 CHAR) CONSTRAINT ID_ADMIN_PK PRIMARY KEY,
PW VARCHAR2(15 char) CONSTRAINT PW_ADMIN_NN NOT NULL);

INSERT INTO ADMIN VALUES('ADMIN1','1111');
INSERT INTO ADMIN VALUES('ADMIN2','2222');
INSERT INTO ADMIN VALUES('ADMIN3','3333');
INSERT INTO ADMIN VALUES('ADMIN4','4444');
INSERT INTO ADMIN VALUES('ADMIN5','5555');
commit;